server:
  port: 90
spring:
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 60000
    password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 1000
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 0
  application:
    name: spring-boot-redis-message
